### ISSUE TITLE
Bug: No such file or directory: '../data/mnist_A.npy'

### ISSUE THREAD

**Issue by karekin** [lihualei71/ScsgAdaptivity#1]
I want to implement SCSG, but I don't know how to get datasets.

Could you please provide the datasets of this article? Or tell me how to get it?

**Comment by lihualei71** [comment]
I have added the datasets and parameter files in `/data`.

**Comment by karekin** [comment]
Thank you very much!

**Comment by karekin** [comment]
Hello Lihua，
I had some problems when I execute `process_data.py`

![image](https://user-images.githubusercontent.com/47046461/160954735-60fce5f7-71ea-481b-9467-056c0671544c.png)

![image](https://user-images.githubusercontent.com/47046461/160954747-bc789bc9-9156-40ac-a96d-d4d1b45c8540.png)

I attempt to deal with it by adding parameters `A = np.load("../data/mnist_A.npy", allow_pickle=True, fix_imports=True, encoding='latin1')` , but failed with following issue.

![image](https://user-images.githubusercontent.com/47046461/160955148-dd06292d-c7bc-4c77-971f-4c3bae37c49b.png)

I guess this is a compatibility issue of pickle but I don't know how to solve it. Do you have any suggestions?

**Comment by lihualei71** [comment]
I can load mnist_A.npy on my machine. According to this post (https://stackoverflow.com/questions/60191681/cannot-load-file-containing-pickled-data-python-npy-i-o), the issue could be with `git lfs`, which I used to upload a file >100MB. 

Could you try loading other datasets? If there is no issue with other datasets, you can try `git lfs pull` to pull mnist_A.npy instead.

**Comment by karekin** [comment]
You are right! When I used `git lfs `to clone , it worked.

Thank you again!

**Comment by karekin** [comment]
Hello Lihua，I've got another problem in `post_process_expr.py`.
![image](https://user-images.githubusercontent.com/47046461/161028448-0cb91687-644c-43f6-866a-7b95e1d3dacd.png)

![image](https://user-images.githubusercontent.com/47046461/161028501-d0288aaa-db81-4ff4-901e-ad7b92a7449b.png)

I guess that the file should have been generated from `expr.py`，but I can't find it.

**Comment by lihualei71** [comment]
Yes, they are generated from `expr.py` and you will see them after running all jobs (via jobs/SCSG_job.sh). I just uploaded all of them to the results/ folder, which I git-ignored previously.

**Comment by karekin** [comment]
`compute_optim.py` has been running for too long. It's really a big project.

when `compute_optim.py` finished, `post_process_expr.py` encountered some trouble. And other files ran successfully. 

![image](https://user-images.githubusercontent.com/47046461/161357295-61fafd05-d4e0-4260-9fe1-20bbe7243bb2.png)



Thank you very much for your patience to answer!
